### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by luzpaz** [DanMiel/QuickMeasure#4]

**Comment by DanMiel** [comment]
Where are License files that need to be added?
Dan

**Comment by luzpaz** [comment]
What LICENSE do you want to use ? 
GPL or LGLP ? or something else?

**Comment by DanMiel** [comment]
You can pick either license since I do not know the difference between them. This program is something I wrote a few months back and thought other users might use it also, so I added more measuring functions.
Dan

**Comment by luzpaz** [comment]
Ok, then lets go with GPL. I'll create a PR to add the file.
