### ISSUE TITLE
Add Screenshots to README

### ISSUE THREAD

**Issue by luzpaz** [DanMiel/QuickMeasure#5]

**Comment by DanMiel** [comment]
Do I just copy/paste pictures?
Dan

**Comment by luzpaz** [comment]
just paste the pictures (ctrl+v) in to this ticket and I"ll take care of the rest.

**Comment by DanMiel** [comment]
![QM1](https://user-images.githubusercontent.com/42722171/201189793-876b9a3c-666a-4ded-a8dc-76c005716ddf.JPG)
![QM2](https://user-images.githubusercontent.com/42722171/201189796-3ebdb936-597f-47a1-bf96-837d6b430add.JPG)

Here are a couple of pictures.

**Comment by luzpaz** [comment]
@DanMiel please merge #1 and then I'll add these afterwards

**Comment by DanMiel** [comment]
If adding the pictures to the file is just pasting them in, I can do that, but first I'll correct the spelling of "Cylinder" in the picture.
Thanks for your help.
Dan
