### ISSUE TITLE
Volume for solid is wrong

### ISSUE THREAD

**Issue by estan** [DanMiel/QuickMeasure#7]
Hi,

I really like your addon, it helped me measure some critical angles at work.

I found an issue when measuring the volume of a solid.

### Steps to Reproduce

- File → New
- In the Part workbench:
    - Click "Create a Cylinder" in the toolbar
    - Select "Cylinder" in the "Tree view"
- In the Quick Measure workbench:
    - Click the quick measure button ("Selecting one feature [...]") in the toolbar

The quick measure popup shows Volume = 1.51 cm^2, which is wrong because:

- The volume of the cylinder should be πr²·h = π·2²·10 = 125.663... mm³
- cm^2 is not a unit of volume

![bild](https://user-images.githubusercontent.com/86675/204841939-a631adbe-5df2-4195-ac74-1b0f91c0e805.png)

I used FreeCAD 0.19 on Ubuntu 22.04, with the addon installed via Tools → Addon manager.

**Comment by DanMiel** [comment]
I glad the add-on is useful. Download the add-on again and let me know if it doesn't work as expected.
Thanks for the report.
Dan

**Comment by estan** [comment]
Can confirm it's correct now, thanks for the quick fix @DanMiel !
